language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/GetValues/GetValues.ino
    - PLATFORMIO_CI_SRC=utilities/GetSlaveID/GetSlaveID.ino
    - PLATFORMIO_CI_SRC=utilities/ChangeSlaveID/ChangeSlaveID.ino

install:
    - pip install -U platformio
    - pio upgrade
    - pio update

script:
- platformio ci --lib="." --board=mayfly
