language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/GetValues/GetValues.ino
    - PLATFORMIO_CI_SRC=utilities/GetSlaveID/GetSlaveID.ino
    - PLATFORMIO_CI_SRC=utilities/ChangeSlaveID/ChangeSlaveID.ino

install:
    - pip install -U platformio
    - pio lib install https://github.com/EnviroDIY/SensorModbusMaster.git
    - pio lib -g install https://github.com/PaulStoffregen/AltSoftSerial.git  # #73, but need the git until Paul S. has a new release
    - pio upgrade
    - pio update

script:
- platformio ci --lib="." --board=mayfly
